package WebService::Freshservice::User::CustomField;

use v5.010;
use strict;
use warnings;
use Method::Signatures 20140224;
use List::MoreUtils qw(any);
use Carp qw( croak );
use JSON qw( encode_json );
use Moo;
use namespace::clean;

# ABSTRACT: Freshservice User Custom Field

# VERSION: Generated by DZP::OurPkg:Version

=head1 SYNOPSIS

  use WebService::Freshservice::User::CustomField;

  my $customfield = WebService::Freshservice::User::CustomField->new( api => $api, id => '1234567890' raw => $data );

Requires an 'WebService::Freshservice::API' object, id of the user and
'raw' data.

=head1 DESCRIPTION

Provides a Freshservice user custom field object. 

=cut

my $Ref = sub {
    croak("api isn't a 'WebService::Freshservice::API' object!") unless $_[0]->DOES("WebService::Freshservice::API");
};

has 'api'    => ( is => 'rw', required => 1, isa => $Ref );
has 'id'     => ( is => 'ro', required => 1 );
has 'field'  => ( is => 'rw', required => 1 );
has 'value'  => ( is => 'rw', required => 1 );

=method update_custom_field

=cut

method update_custom_field {
  my $data->{user}{custom_field}{$self->field} = $self->value;
  $self->api->put_api( "itil/requesters/".$self->id.".json", $data);
  return 1;
}

# Internal method that returns a clean perl data structure
# for encode_json
method TO_JSON {
  return $self->value;
}

1;
